"""Add mission tables and lifecycle

Revision ID: 4e60f9143362
Revises: 7912bf623dee
Create Date: 2025-11-13 19:09:13.656544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e60f9143362'
down_revision: Union[str, Sequence[str], None] = '7912bf623dee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mission_type', sa.String(length=100), nullable=False),
    sa.Column('prep_start_date', sa.Date(), nullable=True),
    sa.Column('prep_end_date', sa.Date(), nullable=True),
    sa.Column('event_start_date', sa.Date(), nullable=False),
    sa.Column('event_end_date', sa.Date(), nullable=False),
    sa.Column('state', sa.Enum('PREP', 'TRAINING', 'EVENT_ACTIVE', 'MISSION_COMPLETE', name='missionstate'), nullable=False),
    sa.Column('points_schema', sa.JSON(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=True),
    sa.Column('notification_preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_state'), 'missions', ['state'], unique=False)
    op.create_index(op.f('ix_missions_user_id'), 'missions', ['user_id'], unique=False)
    op.create_table('event_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mission_id', sa.String(length=36), nullable=False),
    sa.Column('stage_number', sa.Integer(), nullable=False),
    sa.Column('stage_type', sa.String(length=50), nullable=False),
    sa.Column('ride_mode', sa.String(length=50), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bonuses', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_progress_mission_id'), 'event_progress', ['mission_id'], unique=False)
    op.create_table('mission_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mission_id', sa.String(length=36), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('workout_json', sa.JSON(), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_runs_mission_id'), 'mission_runs', ['mission_id'], unique=False)
    op.create_index(op.f('ix_mission_runs_run_date'), 'mission_runs', ['run_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mission_runs_run_date'), table_name='mission_runs')
    op.drop_index(op.f('ix_mission_runs_mission_id'), table_name='mission_runs')
    op.drop_table('mission_runs')
    op.drop_index(op.f('ix_event_progress_mission_id'), table_name='event_progress')
    op.drop_table('event_progress')
    op.drop_index(op.f('ix_missions_user_id'), table_name='missions')
    op.drop_index(op.f('ix_missions_state'), table_name='missions')
    op.drop_table('missions')
    # ### end Alembic commands ###
