"""add_data_connections_tables

Revision ID: 891098f85c97
Revises: 4e60f9143362
Create Date: 2025-11-21 20:42:01.067910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '891098f85c97'
down_revision: Union[str, Sequence[str], None] = '4e60f9143362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apple_health_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('daily_metrics', sa.Text(), nullable=True),
    sa.Column('upload_batch_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apple_health_data_data_date'), 'apple_health_data', ['data_date'], unique=False)
    op.create_index(op.f('ix_apple_health_data_id'), 'apple_health_data', ['id'], unique=False)
    op.create_index(op.f('ix_apple_health_data_user_id'), 'apple_health_data', ['user_id'], unique=False)
    op.create_table('data_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('connection_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('encrypted_credentials', sa.Text(), nullable=True),
    sa.Column('last_refresh_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_refresh_status', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_connections_connection_type'), 'data_connections', ['connection_type'], unique=False)
    op.create_index(op.f('ix_data_connections_id'), 'data_connections', ['id'], unique=False)
    op.create_index(op.f('ix_data_connections_user_id'), 'data_connections', ['user_id'], unique=False)
    op.create_table('oura_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('readiness_score', sa.Integer(), nullable=True),
    sa.Column('hrv_metrics', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oura_data_data_date'), 'oura_data', ['data_date'], unique=False)
    op.create_index(op.f('ix_oura_data_id'), 'oura_data', ['id'], unique=False)
    op.create_index(op.f('ix_oura_data_user_id'), 'oura_data', ['user_id'], unique=False)
    op.create_table('strava_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('strava_activity_id', sa.String(length=50), nullable=False),
    sa.Column('activity_name', sa.String(length=255), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('activity_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metrics', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strava_activities_activity_date'), 'strava_activities', ['activity_date'], unique=False)
    op.create_index(op.f('ix_strava_activities_id'), 'strava_activities', ['id'], unique=False)
    op.create_index(op.f('ix_strava_activities_strava_activity_id'), 'strava_activities', ['strava_activity_id'], unique=False)
    op.create_index(op.f('ix_strava_activities_user_id'), 'strava_activities', ['user_id'], unique=False)
    op.create_table('mission_drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.String(length=36), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('questionnaire', sa.JSON(), nullable=False),
    sa.Column('draft', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_drafts_mission_id'), 'mission_drafts', ['mission_id'], unique=False)
    op.create_index(op.f('ix_mission_drafts_user_id'), 'mission_drafts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mission_drafts_user_id'), table_name='mission_drafts')
    op.drop_index(op.f('ix_mission_drafts_mission_id'), table_name='mission_drafts')
    op.drop_table('mission_drafts')
    op.drop_index(op.f('ix_strava_activities_user_id'), table_name='strava_activities')
    op.drop_index(op.f('ix_strava_activities_strava_activity_id'), table_name='strava_activities')
    op.drop_index(op.f('ix_strava_activities_id'), table_name='strava_activities')
    op.drop_index(op.f('ix_strava_activities_activity_date'), table_name='strava_activities')
    op.drop_table('strava_activities')
    op.drop_index(op.f('ix_oura_data_user_id'), table_name='oura_data')
    op.drop_index(op.f('ix_oura_data_id'), table_name='oura_data')
    op.drop_index(op.f('ix_oura_data_data_date'), table_name='oura_data')
    op.drop_table('oura_data')
    op.drop_index(op.f('ix_data_connections_user_id'), table_name='data_connections')
    op.drop_index(op.f('ix_data_connections_id'), table_name='data_connections')
    op.drop_index(op.f('ix_data_connections_connection_type'), table_name='data_connections')
    op.drop_table('data_connections')
    op.drop_index(op.f('ix_apple_health_data_user_id'), table_name='apple_health_data')
    op.drop_index(op.f('ix_apple_health_data_id'), table_name='apple_health_data')
    op.drop_index(op.f('ix_apple_health_data_data_date'), table_name='apple_health_data')
    op.drop_table('apple_health_data')
    # ### end Alembic commands ###
