# This script generates a daily update for the Tour Coach program, including
# workout plans, readiness scores, and recommendations based on the user's
# data from Oura and Strava.

from dotenv import load_dotenv
from lanterne_rouge.mission_config import load_config
import sys
import os
from lanterne_rouge.monitor import get_oura_readiness, get_ctl_atl_tsb
from lanterne_rouge.reasoner import decide_adjustment
from lanterne_rouge.plan_generator import generate_workout_plan
from lanterne_rouge.peloton_matcher import match_peloton_class
from lanterne_rouge.memory_bus import load_memory, log_observation, log_decision, log_reflection
from datetime import datetime

load_dotenv()


# Helper function to get the agent version
def get_version():
    try:
        with open("VERSION", "r") as f:
            return f.read().strip()
    except FileNotFoundError:
        return "Unknown"



def run():
    # Load mission configuration
    cfg = load_config(os.getenv("MISSION_CONFIG_PATH", "missions/tdf-sim-2025.toml"))

    # Load agent memory
    memory = load_memory()

    # 1. Pull today's data
    readiness_score, hrv_balance, readiness_day = get_oura_readiness()
    ctl, atl, tsb = get_ctl_atl_tsb()

    # Log today's observations to memory
    log_observation({
        "readiness_score": readiness_score,
        "hrv_balance": hrv_balance,
        "readiness_day": readiness_day,
        "ctl": ctl,
        "atl": atl,
        "tsb": tsb,
    })

    # 2. Decide if we need to adjust today's plan
    recommendations = decide_adjustment(
        readiness_score=readiness_score,
        readiness_details={
            "hrv_balance": hrv_balance,
            "readiness_day": readiness_day
        },
        ctl=ctl,
        atl=atl,
        tsb=tsb,
        mission_cfg=cfg,
    )

    # Log decision (recommendations) to memory
    log_decision({"recommendations": recommendations})

    # 3. Get today's workout plan via LLM-driven planner
    workout = generate_workout_plan(cfg, memory)
    today_workout_type = workout["name"]
    today_workout_details = workout.get("description", "")

    # 4. Match to Peloton class
    peloton_class = match_peloton_class(today_workout_type)

    # 5. Read version
    version = get_version()

    # 6. Write the daily update
    today_display_date = datetime.now().strftime("%A, %B %d, %Y")

    summary_lines = []
    summary_lines.append(f"Date: {today_display_date}\n")
    summary_lines.append("Planned Workout:\n")
    summary_lines.append(f"- {today_workout_type} ({today_workout_details})\n")
    summary_lines.append("\nReadiness and Recovery:\n")
    summary_lines.append(
        f"- Readiness Score: {readiness_score if readiness_score else 'Unavailable'}\n"
    )
    summary_lines.append(
        f"- Readiness Day: {readiness_day if readiness_day else 'Unavailable'}\n"
    )
    summary_lines.append(f"- CTL (Fitness): {ctl if ctl else 'Unavailable'}\n")
    summary_lines.append(f"- ATL (Fatigue): {atl if atl else 'Unavailable'}\n")
    summary_lines.append(f"- TSB (Form): {tsb if tsb else 'Unavailable'}\n")
    summary_lines.append("\nRecommendation:\n")
    for rec in recommendations:
        summary_lines.append(f"- {rec}\n")
    summary_lines.append("\nPeloton Class Suggestion:\n")
    summary_lines.append(f"- {peloton_class}\n")
    summary_lines.append("\nNotes:\n")
    summary_lines.append(
        "- Adjust fueling based on today's effort. Stay hydrated and recover smart.\n"
    )
    summary_lines.append(f"\nGenerated by Tour Coach Agent v{version}\n")

    summary = "".join(summary_lines)

    # Ensure output directory exists
    os.makedirs("output", exist_ok=True)

    # Write to file
    with open("output/tour_coach_update.txt", "w") as f:
        f.write(summary)

    # Log reflection (summary) to memory
    log_reflection({"summary": summary})

    print(
        f"✅ Tour Coach Agent v{version} daily update generated: "
        "output/tour_coach_update.txt"
    )

    # Build log dictionary with structured data
    log = {
        "date": today_display_date,
        "workout": {
            "type": today_workout_type,
            "details": today_workout_details,
        },
        "readiness": {
            "score": readiness_score,
            "hrv_balance": hrv_balance,
            "day": readiness_day,
        },
        "ctl": ctl,
        "atl": atl,
        "tsb": tsb,
        "recommendations": recommendations,
        "peloton_class": peloton_class,
        "version": version,
    }
    return summary, log


if __name__ == "__main__":
    run()
