# ────────────────────────────────────────────────────────────────
# MissionConfig – Tour de France Indoor Simulation 2025
# ----------------------------------------------------------------
id          = "tdf-sim-2025"
name        = "Tour de France Indoor Simulation 2025"

# Resolved at runtime from an env var / secret:
athlete_id  = "${STRAVA_ATHLETE_ID}"     # e.g. export STRAVA_ATHLETE_ID=1234567

start_date  = 2025-01-01                 # first day of the block
goal_event  = "Tour de France Indoor Simulation 2025"  
goal_date   = 2025-07-27

[targets]
ctl_peak               = 55        # Adjusted from 80 to reflect sustainable completion
long_ride_minutes      = 75        # Adjusted from 90 to match simulation cap
stage_climb_minutes    = 60
threshold_interval_min = 20

[constraints]
min_readiness = 70
max_rhr       = 56
min_tsb       = -15

[athlete]
ftp           = 128         # Athlete's Functional Threshold Power in watts

# ─────────────────────────────────────────────────────────────
# TDF Points System Configuration
# ─────────────────────────────────────────────────────────────
[tdf_simulation]
enabled = true
start_date = 2025-07-05
end_date = 2025-07-27
total_stages = 21

# Official rest days during the 2025 Tour de France
rest_days = [
    "2025-07-15",  # Rest Day 1 after Stage 10
    "2025-07-22"   # Rest Day 2 after Stage 16
]

# Stage schedule with types - OFFICIAL 2025 Tour de France
[tdf_simulation.stages]
1 = "flat"     # FLAT: Lille Métropole > Lille Métropole (184.9km)
2 = "hilly"    # HILLY: Lauwin-Planque > Boulogne-sur-Mer (209.1km)
3 = "flat"     # FLAT: Valenciennes > Dunkerque (178.3km)
4 = "hilly"    # HILLY: Amiens Métropole > Rouen (174.2km)
5 = "itt"      # ITT: Caen > Caen (33km)
6 = "hilly"    # HILLY: Bayeux > Vire Normandie (201.5km)
7 = "hilly"    # HILLY: Saint-Malo > Mûr-de-Bretagne (197km)
8 = "flat"     # FLAT: Saint-Méen-le-Grand > Laval (171.4km)
9 = "flat"     # FLAT: Chinon > Châteauroux (174.1km)
10 = "mountain" # MOUNTAIN: Ennezat > Le Mont-Dore Puy de Sancy (165.3km)
11 = "flat"    # FLAT: Toulouse > Toulouse (156.8km)
12 = "mountain" # MOUNTAIN: Auch > Hautacam (180.6km) - Mountain finish
13 = "itt"     # ITT: Loudenvielle > Peyragudes (10.9km)
14 = "mountain" # MOUNTAIN: Pau > Luchon-Superbagnères (182.6km) - Mountain finish
15 = "hilly"   # HILLY: Muret > Carcassonne (169.3km)
16 = "mountain" # MOUNTAIN: Montpellier > Mont Ventoux (171.5km) - Mountain finish
17 = "hilly"   # HILLY: Bollène > Valence (160.4km)
18 = "mountain" # MOUNTAIN: Vif > Courchevel Col de la Loze (171.5km) - Mountain finish
19 = "mountain" # MOUNTAIN: Albertville > La Plagne (129.9km) - Mountain finish
20 = "flat"    # FLAT: Nantua > Pontarlier (184.2km)
21 = "flat"    # FLAT: Mantes-la-Ville > Paris Champs-Élysées (132.3km)

# Points structure for different stage types and ride modes
[tdf_simulation.points]
[tdf_simulation.points.flat]
gc = 5
breakaway = 8

[tdf_simulation.points.hilly]
gc = 7
breakaway = 11

[tdf_simulation.points.mountain]
gc = 10
breakaway = 15

[tdf_simulation.points.itt]
gc = 4
breakaway = 6

[tdf_simulation.points.mtn_itt]
gc = 6
breakaway = 9

# Achievement bonus structure
[tdf_simulation.bonuses]
consecutive_5_stages = 5
breakaway_10_stages = 15
all_mountains_breakaway = 10
final_week_complete = 10
all_gc_mode = 25

# Safety thresholds for ride mode recommendations
[tdf_simulation.safety]
force_rest_readiness = 60
force_rest_tsb = -20
prefer_gc_readiness = 75
prefer_gc_tsb = -10
prefer_breakaway_readiness = 80
prefer_breakaway_tsb = -5

# Activity detection settings
[tdf_simulation.detection]
min_stage_duration_minutes = 30
# Power-based thresholds (using Intensity Factor and TSS)
breakaway_intensity_threshold = 0.85  # IF threshold for breakaway effort
breakaway_tss_threshold = 60          # TSS threshold for breakaway effort
gc_intensity_threshold = 0.70         # IF threshold for solid GC effort
gc_tss_threshold = 40                 # TSS threshold for GC effort
# Fallback suffer score for when power data is unavailable
fallback_suffer_threshold = 100       # Suffer score threshold
