name: Daily Coach Run

permissions:
  contents: read
  actions: write
  id-token: write

on:
  schedule:
    - cron: '0 15 * * *'  # 7AM PT = 15:00 UTC
  workflow_dispatch:

jobs:
  run-daily:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Lanterne Rouge
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          TO_PHONE: ${{ secrets.TO_PHONE }}
          # USE_TWILIO: ${{ secrets.USE_TWILIO }}
          # TWILIO_SID: ${{ secrets.TWILIO_SID }}
          # TWILIO_AUTH: ${{ secrets.TWILIO_AUTH }}
          # TWILIO_PHONE: ${{ secrets.TWILIO_PHONE }}
          OURA_TOKEN: ${{ secrets.OURA_TOKEN }}
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
          REPO_OWNER: alponsirenas
          REPO_NAME: lanterne-rouge
          GH_PAT: ${{ secrets.GH_PAT }}
        run: python scripts/daily_run.py

      - name: Commit & push output
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            output/*.txt
            output/*.csv
            lanterne.db           
          author_name: lanterne-rouge-bot
          author_email: bot@users.noreply.github.com
          message: 'chore(data): daily coach output [skip ci]'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
