name: Daily Coach + TDF Morning

permissions:
  contents: write
  actions: write
  id-token: write

on:
  schedule:
    # 7AM PT = 14:00 UTC, only during July TDF period
    - cron: '0 14 * 7 *'
  workflow_dispatch:

jobs:
  daily-with-tdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Daily Coach
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          TO_PHONE: ${{ secrets.TO_PHONE }}
          OURA_TOKEN: ${{ secrets.OURA_TOKEN }}
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
          STRAVA_ATHLETE_ID: ${{ secrets.STRAVA_ATHLETE_ID }}
          REPO_OWNER: alponsirenas
          REPO_NAME: lanterne-rouge
          GH_PAT: ${{ secrets.GH_PAT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          USE_LLM_REASONING: "true"
          OPENAI_MODEL: "gpt-4-turbo-preview"
          USE_TWILIO: ${{ secrets.USE_TWILIO }}
        run: python scripts/daily_run.py

      - name: Run TDF Morning Briefing
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          TO_PHONE: ${{ secrets.TO_PHONE }}
          OURA_TOKEN: ${{ secrets.OURA_TOKEN }}
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
          STRAVA_ATHLETE_ID: ${{ secrets.STRAVA_ATHLETE_ID }}
          REPO_OWNER: alponsirenas
          REPO_NAME: lanterne-rouge
          GH_PAT: ${{ secrets.GH_PAT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          USE_LLM_REASONING: "true"
          OPENAI_MODEL: "gpt-4-turbo-preview"
          USE_TWILIO: ${{ secrets.USE_TWILIO }}
        run: python scripts/morning_tdf_briefing.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'output/*.txt output/*.csv output/tdf_points.json memory/lanterne.db'
          author_name: lanterne-rouge-daily-bot
          author_email: daily-bot@users.noreply.github.com
          message: 'chore(daily): coach output + TDF briefing [skip ci]'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_PAT }}
          branch: daily-tdf-output-${{ github.run_id }}
          commit-message: 'chore(daily): coach output + TDF briefing [skip ci]'
          title: 'Daily Coach Output + TDF Briefing'
          body: 'This PR contains the daily coach output and TDF morning briefing. Daily training recommendation, TDF stage briefing and ride mode recommendation, updated points tracking data. Automatically generated by the Daily Coach + TDF workflow.'
          base: main