name: TDF Morning Briefing

permissions:
  contents: write
  actions: write
  id-token: write

on:
  schedule:
    # 6AM PT = 13:00 UTC, every day during TDF season
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  tdf-morning-briefing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run TDF Morning Briefing
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          TO_PHONE: ${{ secrets.TO_PHONE }}
          OURA_TOKEN: ${{ secrets.OURA_TOKEN }}
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
          STRAVA_ATHLETE_ID: ${{ secrets.STRAVA_ATHLETE_ID }}
          REPO_OWNER: alponsirenas
          REPO_NAME: lanterne-rouge
          GH_PAT: ${{ secrets.GH_PAT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          USE_LLM_REASONING: "true"
          OPENAI_MODEL: "gpt-4-turbo-preview"
          USE_TWILIO: ${{ secrets.USE_TWILIO }}
        run: python scripts/morning_tdf_briefing.py

      - name: Update TDF Documentation
        env:
          STRAVA_ATHLETE_ID: ${{ secrets.STRAVA_ATHLETE_ID }}
        run: |
          echo "Updating TDF documentation with morning briefing..."
          python scripts/integrate_tdf_docs.py

      - name: Commit TDF Points Data
        uses: EndBug/add-and-commit@v9
        with:
          add: 'output/tdf_points.json output/*.txt output/*.csv docs_src/tdf-simulation/stages/*.md docs_src/tdf-simulation/index.md mkdocs.yml'
          author_name: lanterne-rouge-tdf-bot
          author_email: tdf-bot@users.noreply.github.com
          message: 'feat(tdf): morning briefing and points update [skip ci]'
          github_token: ${{ secrets.GH_PAT }}