name: TDF Morning Briefing

permissions:
  contents: write
  actions: write
  id-token: write

on:
  schedule:
    - cron: '0 13 * 7 *'  # 6AM PT = 13:00 UTC, only in July
  workflow_dispatch:  # Allow manual trigger

jobs:
  tdf-morning-briefing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run TDF Morning Briefing
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          TO_PHONE: ${{ secrets.TO_PHONE }}
          OURA_TOKEN: ${{ secrets.OURA_TOKEN }}
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
          REPO_OWNER: alponsirenas
          REPO_NAME: lanterne-rouge
          GH_PAT: ${{ secrets.GH_PAT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          USE_TWILIO: ${{ secrets.USE_TWILIO }}
        run: python scripts/morning_tdf_briefing.py

      - name: Commit TDF Points Data
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            output/tdf_points.json
            output/*.txt
            output/*.csv
          author_name: lanterne-rouge-tdf-bot
          author_email: tdf-bot@users.noreply.github.com
          message: 'feat(tdf): morning briefing and points update [skip ci]'